### ISSUE TITLE
Startup Dev

### ISSUE THREAD

**Issue by kacollins** [kacollins/2022-10-22-workshop#10]
Add Startup Dev as a sponsor between Ghost Agency and Sugar Security.

**Comment by alkrauss48** [comment]
@kacollins sounds like someone needs to tag this repo with a `hacktoberfest` 👀 
<img width="457" alt="Screen Shot 2022-10-09 at 12 01 17 AM" src="https://user-images.githubusercontent.com/1478883/194738935-b65f2d50-657a-42cb-ba9e-858007e00a06.png">

**Comment by kacollins** [comment]
I will look at your PR later today and mark it as hacktoberfest-accepted. See my post in Slack for more info.

**Comment by kacollins** [comment]
Done in #11
